# play.yml
---

# Buildserver

# import the SSH initialization tasks
- import_playbook: playbooks/ssh/initialize_known_hosts.yml

# Configure buildserver
# - import_playbook: playbooks/server/config_server.yml

# install Jenkins
- import_playbook: playbooks/jenkins/install/install_jenkins.yml

# user
- import_playbook: playbooks/jenkins/user/jenkins_admin_user.yml

# plugins
- import_playbook: playbooks/jenkins/install_plugins/plugins.yml

# app
# - import_playbook: app/p3ops-demo-app/ansible/site.yml

# node 
- import_playbook: playbooks/jenkins/node/config_credentials.yml
- import_playbook: playbooks/jenkins/node/config_ssh_node.yml
- import_playbook: playbooks/jenkins/node/create_node.yml
- import_playbook: playbooks/jenkins/node/setup_node.yml

# pipeline
# - import_playbook: playbooks/jenkins/pipeline/create_dotnet_pipeline.yml
- import_playbook: playbooks/jenkins/pipeline/create_test_pipeline.yml

# security
- import_playbook: playbooks/jenkins/pipeline/secure_credentials.yml







