---
- hosts: buildserver
  become: yes
  vars_files:
    - ../../vars/main.yml
    - "{{ vault_path }}"
    - "{{ SSH_SECRET_PATH }}"
    - "{{ auth_path }}"
    - "{{ sql_path }}"

  tasks:
    - name: Retrieve Jenkins Crumb
      uri:
        url: '{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: yes
        return_content: yes
      register: crumb

    - name: Read the private key
      ansible.builtin.slurp:
        src: "{{ SSH_PRIVATE_KEY }}"
      register: private_key

    - name: Decrypt M2M Client ID
      debug:
        msg: "{{ M2MClientId }}"

    - name: Decrypt M2M Client Secret
      debug:
        msg: "{{ M2MClientSecret }}"

    - name: Decrypt Blazor Client ID
      debug:
        msg: "{{ BlazorClientId }}"

    - name: Decrypt Blazor Client Secret
      debug:
        msg: "{{ BlazorClientSecret }}"

    - name: Add Auth0 credential to Jenkins
      community.general.jenkins_script:
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        script: "{{ lookup('template', '/vagrant/ansible/playbooks/jenkins/files/security/auth0.groovy') }}"
      loop:
        - M2MClientId
        - M2MClientSecret
        - BlazorClientId
        - BlazorClientSecret

    - name: Decrypt SQL Connection String
      debug:
        msg: "{{ SQLConnectionString }}"

    - name: Add SQL connection string to Jenkins
      community.general.jenkins_script:
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        script: "{{ lookup('template', '/vagrant/ansible/playbooks/jenkins/files/security/db_credentials.groovy') }}"
      loop:
        - SQLConnectionString

    - name: Retrieve Jenkins credentials
      community.general.jenkins_script:
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        script: |
          import com.cloudbees.plugins.credentials.Credentials
          Set<Credentials> allCredentials = new HashSet<Credentials>();

          // Retrieve credentials from Jenkins instance
          def creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
                com.cloudbees.plugins.credentials.Credentials.class
          );
          allCredentials.addAll(creds)

          // Also check credentials from folders in Jenkins
          Jenkins.instance.getAllItems(com.cloudbees.hudson.plugins.folder.Folder.class).each{ f ->
            creds = com.cloudbees.plugins.credentials.CredentialsProvider.lookupCredentials(
                  com.cloudbees.plugins.credentials.Credentials.class, f)
            allCredentials.addAll(creds)
          }

          // Print credential details
          for (c in allCredentials) {
            println(c.id)
            if (c.properties.username) {
              println("   description: " + c.description)
            }
            if (c.properties.username) {
              println("   username: " + c.username)
            }
            if (c.properties.password) {
              println("   password: " + c.password)
            }
            if (c.properties.passphrase) {
              println("   passphrase: " + c.passphrase)
            }
            if (c.properties.secret) {
              println("   secret: " + c.secret)
            }
            if (c.properties.privateKeySource) {
              println("   privateKey: " + c.getPrivateKey())
            }
            println("")
          }
