- hosts: buildserver
  become: yes
  vars_files:
    - ../../vars/main.yml
    - "{{ vault_path }}"
    - "{{ SSH_SECRET_PATH }}"

  tasks:
    - name: Check if SSH private key already exists
      ansible.builtin.stat:
        path: "{{ SSH_PRIVATE_KEY }}"
      register: ssh_key_stat

    - name: Ensure SSH directory exists
      file:
        path: "/vagrant/src/buildserver/ansible/playbooks/jenkins/files/ssh/"
        state: directory
        mode: '0755'

    - name: Generate Ed25519 SSH key pair
      ansible.builtin.command: ssh-keygen -t ed25519 -f "{{ SSH_PRIVATE_KEY }}" -N ""

      register: ssh_keygen_result
      when: not ssh_key_stat.stat.exists
    
    - name: Check if SSH private key already exists
      ansible.builtin.stat:
        path: "{{ SSH_PRIVATE_KEY }}"
      register: ssh_key_stat
   
    - name: Set ownership of the SSH key to the Jenkins user
      file:
        path: "{{ SSH_PRIVATE_KEY }}"
        owner: jenkins
        group: jenkins
        mode: '0600'

    - name: Set permissions for the private key
      ansible.builtin.file:
        path: "{{ SSH_PRIVATE_KEY }}"
        mode: '0600'
      when: ssh_keygen_result.changed or not ssh_key_stat.stat.exists

    - name: Read the private key
      ansible.builtin.slurp:
        src: "{{ SSH_PRIVATE_KEY }}"
      register: private_key
      when: ssh_key_stat.stat.exists

    - name: Read the public key
      ansible.builtin.slurp:
        src: "{{ SSH_PRIVATE_KEY }}.pub"
      register: public_key
      when: ssh_keygen_result.changed or not ssh_key_stat.stat.exists

    - name: Retrieve Jenkins Crumb
      uri:
        url: '{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb)'
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: yes
        return_content: yes
      register: crumb

    - name: Read the private key
      ansible.builtin.slurp:
        src: "{{ SSH_PRIVATE_KEY }}"
      register: private_key
      when: ssh_key_stat.stat.exists


    - name: Add SSH credential to Jenkins
      community.general.jenkins_script:
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"
        script: "{{ lookup('template', '/vagrant/ansible/playbooks/jenkins/files/ssh/add_ssh_key.groovy') }}"
    
