- name: Create Jenkins dotnet pipeline
  hosts: buildserver
  gather_facts: no
  vars_files:
    - ../../vars/main.yml
    - "{{ secrets_path }}"
  tasks:
    - name: Install pip
      apt:
        name: python3-pip
        state: present
      become: yes

    - name: Install python-jenkins using pip3
      pip:
        name: python-jenkins
        state: present
        executable: pip3
      become: true

    - name: Ensure .ssh directory exists
      file:
        path: /home/vagrant/.ssh
        state: directory
        mode: '0700'
        owner: vagrant
        group: vagrant

    - name: Ensure known_hosts file exists
      file:
        path: /home/vagrant/.ssh/known_hosts
        state: touch
        mode: '0600'
        owner: vagrant
        group: vagrant

    - name: Scan and register Github fingerprints
      command: "ssh-keyscan -t ed25519 github.com"
      register: host_keys
      become: yes

    - name: Add Github fingerprints keys to known_hosts
      lineinfile:
        path: "/var/lib/jenkins/.ssh/known_hosts"
        line: "{{ item }}"
      with_items: "{{ host_keys.stdout_lines }}"
      become: yes
    
    - name: Add Github fingerprints keys to known_hosts
      lineinfile:
        path: "/home/vagrant/.ssh/known_hosts"
        line: "{{ item }}"
      with_items: "{{ host_keys.stdout_lines }}"
      become: yes
    
    - name: Check if config-acc.xml exists
      stat:
        path: /vagrant/ansible/playbooks/jenkins/files/pipeline/config-acc.xml
      register: file_check

    - debug:
        var: file_check


    - name: Read the config.xml file
      slurp:
        src: "{{ config_acc_file }}"
      register: config_xml

    - name: Create Jenkins pipeline job
      jenkins_job:
        name: "Dotnet-Acceptance-Pipeline"
        config: "{{ config_xml.content | b64decode }}"
        state: present
        url: "{{ jenkins_url }}"
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_password }}"

