---
- name: Create a vault password file in /tmp
  hosts: buildserver
  become: yes
  tasks:
    - name: create vault_password.txt file
      copy:
        dest: /tmp/vault_password.txt
        content: "rise"
        mode: '0600'